import Foundation

struct EnterpriseSignatureMetadata: Codable, Equatable, Hashable, Sendable {
    var scheme: String
    var keyID: String?
    var signature: String?
}

/// The per-employee policy snapshot generated by the workspace server.
/// `nil` allowlists mean unrestricted on that axis; empty arrays mean nothing is allowed.
struct EnterprisePolicy: Codable, Equatable, Sendable {
    var tenantID: String
    var tenantName: String
    var workspaceSlug: String
    var companyCode: String
    var membershipID: String
    var userEmail: String
    var displayName: String?
    var roleIDs: [String]
    var roleNames: [String]
    var deviceID: String
    var allowedModelFormats: [String]?
    var allowedModelIDs: [String]?
    var allowedRemoteBackendIDs: [String]?
    var allowedRemoteEndpointTypes: [String]?
    var allowedToolNames: [String]?
    /// Optional MCP governance. Missing fields preserve consumer defaults.
    var mcpEnabled: Bool? = nil
    var allowedMCPTransports: [String]? = nil
    var allowedMCPServerIDs: [String]? = nil
    var allowedMCPToolAliases: [String]? = nil
    var mcpLocalProcessesAllowed: Bool? = nil
    var mcpSamplingAllowed: Bool? = nil
    var mcpElicitationAllowed: Bool? = nil
    var allowedDatasetIDs: [String]
    var requiresOffGrid: Bool
    var remoteInferenceAllowed: Bool
    var datasetDownloadAllowed: Bool
    /// "full" (models/tools/backends governed) or "datasets" (datasets only).
    /// Optional for policies cached before the field existed; treat nil as "full".
    var governanceMode: String?
    /// Max days the device may go without a successful sync before it wipes all company
    /// data locally (offline-enforced dead-man's switch). nil/0 = unlimited.
    /// Optional for policies cached before the field existed.
    var reconnectIntervalDays: Int?
    var issuedAt: Date
    var expiresAt: Date
    var policyVersion: Int
    var signatureMetadata: EnterpriseSignatureMetadata

    static func decoder() -> JSONDecoder {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return decoder
    }

    static func encoder() -> JSONEncoder {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        return encoder
    }
}

struct EnterpriseHashMetadata: Codable, Equatable, Sendable {
    var algorithm: String
    var contentHash: String?
}

struct EnterpriseDatasetManifest: Codable, Equatable, Sendable {
    var enterpriseDatasetID: String
    /// LocalDataset-compatible ID: "Enterprise/<enterpriseDatasetID>".
    var datasetID: String
    var tenantID: String
    var name: String
    var description: String?
    var version: Int
    var allowedRoleIDs: [String]
    var embeddingModelID: String?
    var chunkCount: Int
    var createdAt: Date
    var updatedAt: Date
    var sourceMetadata: [String: EnterpriseJSONValue]?
    var hashMetadata: EnterpriseHashMetadata?
    var signatureMetadata: EnterpriseSignatureMetadata?
}

struct EnterpriseDatasetFile: Codable, Equatable, Sendable {
    var relPath: String
    var sizeBytes: Int64
    var sha256: String

    enum CodingKeys: String, CodingKey {
        case relPath = "rel_path"
        case sizeBytes = "size_bytes"
        case sha256
    }
}

/// Minimal JSON value for free-form server metadata.
enum EnterpriseJSONValue: Codable, Equatable, Sendable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case null

    init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let value = try? container.decode(Bool.self) {
            self = .bool(value)
        } else if let value = try? container.decode(Double.self) {
            self = .number(value)
        } else if let value = try? container.decode(String.self) {
            self = .string(value)
        } else {
            // Nested containers are not needed for v1 metadata; collapse to null.
            self = .null
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .string(let value): try container.encode(value)
        case .number(let value): try container.encode(value)
        case .bool(let value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }
}

// MARK: - Connection state

enum EnterpriseConnectionState: Equatable, Sendable {
    case none
    case connecting
    case awaitingEmailVerification(enrollmentID: String)
    case pendingApproval(enrollmentID: String)
    case connected
    case policyExpired
    case deviceRevoked
    case policyInvalid
    case disconnected

    var isEnrolledOnDevice: Bool {
        switch self {
        case .connected, .policyExpired, .deviceRevoked, .policyInvalid:
            return true
        default:
            return false
        }
    }
}

/// Durable, non-secret enrollment context (the device token itself lives in the Keychain).
struct EnterpriseStoredContext: Codable, Equatable {
    enum Phase: String, Codable {
        case awaitingCode
        case pendingApproval
        case connected
        case revoked
        case invalid
        case disconnected
    }

    var phase: Phase
    var companyCode: String
    var tenantName: String?
    var email: String
    var enrollmentID: String?
}

/// How the cached policy should be enforced right now.
enum EnterpriseEnforcementStatus: String, Codable, Equatable, Sendable {
    /// Policy is trusted (possibly expired but within grace).
    case valid
    /// Server said 410: restrictions stay in force, enterprise datasets are denied.
    case revoked
    /// Signature/decode/token failure: restrictions stay in force, enterprise datasets are denied.
    case invalid
}

/// What `EnterprisePolicyGate` enforces; persisted so enforcement survives relaunch offline.
struct EnterpriseGateSnapshot: Codable, Equatable, Sendable {
    var policy: EnterprisePolicy
    var status: EnterpriseEnforcementStatus
}

// MARK: - API response payloads

struct EnterpriseLookupResponse: Codable, Sendable {
    var tenantName: String
    var slug: String
}

struct EnterpriseEnrollStartResponse: Codable, Sendable {
    var enrollmentID: String
    var tenantName: String?
    var debugCode: String?
}

struct EnterpriseEnrollResultResponse: Codable, Sendable {
    var status: String // approved | pending_approval | denied | awaiting_code | completed
    var deviceToken: String?
    var deviceID: String?
    var policy: EnterprisePolicy?
    var enrollmentID: String?
}

struct EnterpriseDatasetListResponse: Codable, Sendable {
    var datasets: [EnterpriseDatasetManifest]
}

struct EnterpriseDatasetFilesResponse: Codable, Sendable {
    var files: [EnterpriseDatasetFile]
}

// MARK: - Storage locations

enum EnterprisePolicyStorage {
    nonisolated(unsafe) static var directoryOverrideForTesting: URL?

    static var directory: URL {
        if let override = directoryOverrideForTesting { return override }
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        return base.appendingPathComponent("Enterprise", isDirectory: true)
    }

    static var snapshotURL: URL { directory.appendingPathComponent("policy.json") }
    static var rawPayloadURL: URL { directory.appendingPathComponent("policy-raw.json") }
    static var contextURL: URL { directory.appendingPathComponent("context.json") }

    static func ensureDirectory() {
        let fm = FileManager.default
        guard !fm.fileExists(atPath: directory.path) else { return }
        try? fm.createDirectory(at: directory, withIntermediateDirectories: true)
        var url = directory
        var values = URLResourceValues()
        values.isExcludedFromBackup = true
        try? url.setResourceValues(values)
    }

    static func loadSnapshot() -> EnterpriseGateSnapshot? {
        guard let data = try? Data(contentsOf: snapshotURL) else { return nil }
        return try? EnterprisePolicy.decoder().decode(EnterpriseGateSnapshot.self, from: data)
    }

    static func saveSnapshot(_ snapshot: EnterpriseGateSnapshot, rawPayload: Data?) {
        ensureDirectory()
        if let data = try? EnterprisePolicy.encoder().encode(snapshot) {
            try? data.write(to: snapshotURL, options: [.atomic, .completeFileProtectionUntilFirstUserAuthentication])
        }
        if let rawPayload {
            try? rawPayload.write(to: rawPayloadURL, options: [.atomic, .completeFileProtectionUntilFirstUserAuthentication])
        }
    }

    static func loadContext() -> EnterpriseStoredContext? {
        guard let data = try? Data(contentsOf: contextURL) else { return nil }
        return try? JSONDecoder().decode(EnterpriseStoredContext.self, from: data)
    }

    static func saveContext(_ context: EnterpriseStoredContext) {
        ensureDirectory()
        if let data = try? JSONEncoder().encode(context) {
            try? data.write(to: contextURL, options: [.atomic, .completeFileProtectionUntilFirstUserAuthentication])
        }
    }

    static func clearAll() {
        let fm = FileManager.default
        try? fm.removeItem(at: snapshotURL)
        try? fm.removeItem(at: rawPayloadURL)
        try? fm.removeItem(at: contextURL)
    }
}
